version: '3.7'
services: 
  db-e2e-cloud-storage:
    image: mongo:4.4.1
    container_name: db-e2e-cloud-storage
    volumes: 
      - ./mongo-volume:/data/db
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
    networks: 
      - e2e-cloud-storage-network
    ports: 
      - 27017:27017
  
  s3storage-e2e-cloud-storage:
    image: minio/minio:RELEASE.2020-11-10T21-02-24Z
    container_name: s3storage-e2e-cloud-storage
    environment:
      - BUCKET_NAME=e2e-cloud-storage
      - MINIO_ACCESS_KEY=accesskey
      - MINIO_SECRET_KEY=secretkey
    volumes:
      - s3-data-e2e-cloud-storage:/data
    entrypoint: sh
    command: -c 'mkdir -p /data/e2e-cloud-storage && /usr/bin/minio server /data'
    networks:
      - e2e-cloud-storage-network
    ports:
      - 9010:9000

volumes: 
  db-e2e-cloud-storage:
    driver: local
  s3-data-e2e-cloud-storage:
    driver: local

networks: 
  e2e-cloud-storage-network:
    name: e2e-cloud-storage-net
