# Generated by Django 3.0.5 on 2020-11-29 13:06

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MinioMeta',
            fields=[
                ('uuid', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('oaep', jsonfield.fields.JSONField(default=dict)),
                ('pss', jsonfield.fields.JSONField(default=dict)),
                ('dataNameKey', jsonfield.fields.JSONField(default=dict)),
            ],
        ),
    ]
