# Generated by Django 3.0.5 on 2020-11-29 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miniometa',
            name='uuid',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
