# Generated by Django 3.0.5 on 2020-11-29 17:29

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('django_backend', '0002_auto_20201129_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='miniometa',
            name='passwordKey',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
