# Generated by Django 3.0.5 on 2020-11-28 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_backend', '0002_auto_20201127_0904'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=65)),
            ],
        ),
    ]
