# Generated by Django 3.0.5 on 2020-11-30 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_backend', '0003_miniometa_passwordkey'),
    ]

    operations = [
        migrations.RenameField(
            model_name='miniometa',
            old_name='oaep',
            new_name='rsaOAEP',
        ),
        migrations.RenameField(
            model_name='miniometa',
            old_name='pss',
            new_name='rsaPSS',
        ),
    ]
