# Generated by Django 3.0.5 on 2020-11-28 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_backend', '0003_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
