# Generated by Django 3.0.5 on 2020-11-28 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_backend', '0004_delete_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('ersteller', models.CharField(max_length=20)),
            ],
        ),
    ]
