# Generated by Django 3.0.5 on 2020-11-28 22:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('django_backend', '0006_auto_20201128_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='id',
            field=models.AutoField(auto_created=True, default=django.utils.timezone.now, primary_key=False, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
