name: publish docker to github

on:
  push:
    branches:
      - main

jobs:
  build-backend:  
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: publish to registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: software-sicherheit/backend/e2e-cloud-backend:latest
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: docker.pkg.github.com
